name: Test GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  simple-test-job:
    name: Run Simple Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print Hello Message
        run: echo "Hello Dina! Your DevOps pipeline is successfully running on Ubuntu!"

      - name: Show Files in Repository
        run: ls -la

      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: false
          tags: dinaalmahrouqy/ci-cd:latest
        

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: dinaalmahrouqy
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: push to docker hub
        uses: docker/login-action@v2
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: dinaalmahrouqy/ci-cd:latest
        
