name: Test GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  simple-test-job:
    name: Run Simple Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print Hello Message
        run: echo "Hello Dina! Your DevOps pipeline is successfully running on Ubuntu!"

      - name: Show Files in Repository
        run: ls -la


      - name: build docker image
        uses: actions/build-push-action@v2
        with:
          context: ./worker
          dockerfile: ./worker/Dockerfile
          push: false
          tags: dinaalmahrouqy/CI-CD:latest


        
